<div class="col-md-12">
	<h1>Contributors</h1>
	<p class="lead">Current and active contributors of Chakra.</p>
	<?php
		echo PrintContributor("boom1992.png",
			"Lukas Appelhans",
			"boom1992",
			"lukas.appelhans@chakraos.org",
			"Unknown",
			"#",
			"boom1992.com",
			"Developer (Akabei)",
			"German, English",
			"Germany",
			"1992");
		echo PrintContributor("tetris4.jpg",
			"Neophytos Kolokotronis",
			"tetris4",
			"tetris4@chakraos.org",
			"Unknown",
			"#",
			"N/A",
			"Communicator",
			"English, Greek",
			"N/A",
			"N/A");
		echo PrintContributor("placeholder.png",
			"Fabian Kosmale",
			"Inkane",
			"N/A",
			"N/A",
			"Unknown",
			"#",
			"Sr. Packager",
			"N/A",
			"N/A",
			"N/A");
		echo PrintContributor("totte.jpg",
			"H W Tovetjärn",
			"totte",
			"totte@chakraos.org",
			"0xe845736251a4d4c0",
			"https://pgp.mit.edu/pks/lookup?op=vindex&search=0xE845736251A4D4C0",
			"N/A",
			"Administrator",
			"English",
			"Sweden",
			"1986");
		echo PrintContributor("placeholder.png",
			"Luca Giambonini",
			"almack",
			"almack@chakraos.org",
			"Unknown",
			"#",
			"almack.ch",
			"Sr. Packager",
			"Italian, English, French",
			"Switzerland",
			"");
		echo PrintContributor("placeholder.png",
			"",
			"gallaecio",
			"",
			"Unknown",
			"#",
			"",
			"Sr. Packager",
			"",
			"",
			"");
		echo PrintContributor("placeholder.png",
			"Ryan Shipp",
			"george2",
			"chakra@rshipp.com",
			"Unknown",
			"#",
			"rshipp.com",
			"Developer (Kapudan)",
			"English",
			"USA",
			"");
		echo PrintContributor("gcala.png",
			"Giuseppe Calà",
			"gcala",
			"",
			"Unknown",
			"#",
			"",
			"Sr. Packager",
			"",
			"Italy",
			"1973");
		echo PrintContributor("placeholder.png",
			"",
			"dezponia",
			"",
			"Unknown",
			"#",
			"",
			"",
			"",
			"",
			"");
		echo PrintContributor("placeholder.png",
			"Xuetian Weng",
			"csslayer",
			"",
			"Unknown",
			"#",
			"csslayer.info",
			"Sr. Packager",
			"Chinese, English",
			"China",
			"1990");
		echo PrintContributor("placeholder.png",
			"",
			"brli",
			"",
			"Unknown",
			"#",
			"",
			"Sr. Packager",
			"",
			"",
			"");
		echo PrintContributor("franzmari.png",
			"Francesco Marinucci",
			"franzmari",
			"franzmari@chakra-project.it",
			"Unknown",
			"#",
			"franzmari.wordpress.com",
			"Sr. Packager",
			"English, Italian",
			"Italy",
			"1986");
		echo PrintContributor("placeholder.png",
			"Samir Benmendil",
			"ram-z",
			"ram-z@chakraos.org",
			"Unknown",
			"#",
			"",
			"Sr. Packager, Developer (Tribe)",
			"English, French, German",
			"",
			"");
		echo PrintContributor("placeholder.png",
			"Jeff Huang",
			"s8321414",
			"s8321414@chakraos.org",
			"Unknown",
			"#",
			"osiris-s8321414.blogspot.com",
			"Sr. Packager",
			"Traditional Chinese, English",
			"Taiwan",
			"1994");
	?>
</div>
