<?php
    function PrintContributor($image, $name, $alias, $email, $website, $roles, $languages, $country, $born)
    {
        return "<a name='$alias'></a>"
               . "<tr>"
               . "<td>"
               . "<img style='margin:auto;' width='120' height='148' class='img-rounded' src='static/img/contributors/" . $image . "' alt='" . $image . "' />"
               . "</td>"
               . "<td>"
               . "<h3 style='margin-top:0px;'>$alias</h3>"
               . "<table>"
               . "<tr>"
               . "<th>"
               . "Name:"
               . "</th>"
               . "<td>"
               . "$name"
               . "</td>"
               . "</tr>"
               . "<tr>"
               . "<th>"
               . "Email:"
               . "</th>"
               . "<td>"
               . "$email"
               . "</td>"
               . "</tr>"
               . "<tr>"
               . "<th>"
               . "Roles:"
               . "</th>"
               . "<td>"
               . $roles
               . "</td>"
               . "</tr>"
               . "<tr>"
               . "<th>"
               . "Website:"
               . "</th>"
               . "<td>"
               . "$website"
               . "</td>"
               . "</tr>"
               . "<tr>"
               . "<th>"
               . "Born:"
               . "</th>"
               . "<td>"
               . "$born"
               . "</td>"
               . "</tr>"
               . "<tr>"
               . "<th>"
               . "Country:"
               . "</th>"
               . "<td>"
               . "$country"
               . "</td>"
               . "</tr>"
               . "<tr>"
               . "<th>"
               . "Languages:"
               . "</th>"
               . "<td>"
               . $languages
               . "</td>"
               . "</tr>"
               . "</table>"
               . "</td>"
               . "</tr>"
               . "<br>";
    }
?>
