<div class="col-md-12">
    <h1>Welcome to Chakra</h1>
    <p>The Chakra Project brings a ground-up Linux distribution, a <a href="http://en.wikipedia.org/wiki/Free_software">free software</a> showcase project created by a bunch of <a href="chakraos.org/?who">people</a> who like the <a href="http://en.wikipedia.org/wiki/KISS_principle">KISS</a> principles, the elegance of the <a href="http://www.kde.org/workspaces/plasmadesktop/">Plasma Desktop</a> and a bundlesystem to support well known Gtk applications. One way to support this project is to use the default search engine set in this browser. <a href="http://duckduckgo.com/about.html">DuckDuckGo</a> supports opensource projects like this one by sharing revenue generated by search clicks.  These funds are used to maintain our infrastructure of servers used for building packages and hosting the website. You can use the following Chakra-<a href="https://duckduckgo.com/bang.html" title="!bangs">!bangs</a> to search our website faster and easier: !chakrapkg, !chakraforum, !chakrawiki, !ccr.</p>
    <table class="centered">
        <tr>
            <th><a href="https://duckduckgo.com/?t=chakra"><img align="middle" src="img/icon/duck.png" border="0" alt="" /></a></th>
            <th><iframe src="http://duckduckgo.com/search.html?prefill=Search duckDuckGo" style="overflow:hidden;margin-left:10px;padding:0;width:408px;height:40px;" frameborder="0"></iframe></th>
        </tr>
    </table>
    <table class="index" width="720px" border="0" align="center">
        <tr>
            <th width="360px" align="center"><p class="index">DuckDuckGo does not store any personal information, e.g. IP addresses or user agents: <a href="http://duckduckgo.com/privacy.html">see their privacy policy</a> for details.<br />More about the consequences of tracking as it applies to search results in the  <a href="http://donttrack.us/">donttrack.us</a> and <a href="http://dontbubble.us/">dontbubble.us</a> infographics.</p><br /><p>For more to explain why you should care:<br /><a href="https://duckduckgo.com/privacy.html#s1">Why You should Care - Search Leakage</a><br /><a href="https://duckduckgo.com/privacy.html#s2">Why You Should Care - Search History</a><br /><a href="https://duckduckgo.com/privacy.html#s3">Information Not collected</a><br /><a href="https://duckduckgo.com/privacy.html#s4">information Collected</a><br /><a href="https://duckduckgo.com/privacy.html#s5">Information Shared</a><br /></p><br />
            </th>
        </tr>
    </table>
</div>
