<div class="col-md-12">
    <h1>About</h1>
	<h2>What is Chakra?</h2>
	<p>Chakra is a GNU/Linux distribution with an emphasis on KDE and Qt technologies that focuses on <a href="http://en.wikipedia.org/wiki/KISS_principle">simplicity</a> from a technical standpoint and <a href="http://en.wikipedia.org/wiki/Free_software">free software</a>.</p>
	<p>The goal is provide a fast, user-friendly and powerful <a href="http://en.wikipedia.org/wiki/Live_CD">Live ISO</a> and Linux distribution specifically made for the <a href="http://www.kde.org">KDE</a> <a href="http://www.kde.org/workspaces/plasmadesktop">Plasma desktop</a>.</p>
	<p>With a new concept of <a href="https://chakraos.org/wiki/index.php?title=Chakra_Linux#The_Half-Rolling_Release_Model">half-rolling releases</a>, our <a href="wiki/index.php?title=Chakra_Tools">graphical tools</a> and a small but strong and diverse <a href="https://chakraos.org/forum/">community</a>, this is the computing environment you may have been waiting for!  It is especially made for those who truly want to learn something about Linux and yet not want to deal with excessive administrative overhead to enjoy the KDE Plasma desktop.</p>
	<h2>History</h2>
	<p>Chakra was born on the Internet, in a small shady corner of the <a href="http://freenode.net/">Freenode network</a>, where the KDEmod developers met one day and decided to create an awesome little Live ISO based on Arch Linux. Of course these goals had to be emphasized a little bit more, and soon after the initial thoughts and discussions we started to write up plans, schedules and develop like there is no tomorrow, while not forgetting the fun and keeping it relaxed. Chakra is our baby. A lot of efforts, time and countless hours of writing code and testing stuff have been put into it so far, but that was just the beginning.</p>
	<h2>Goals</h2>
	<p>Our goal with Chakra is to provide an operating system for desktops that is easy to use, but still has all the functionality, clarity, power and speed of a <a href="http://en.wikipedia.org/wiki/KISS_principle">KISS</a> operating system. In the long term, we want to build an operating system that meets most requirements desktop users have today, like easy installation of software, graphical system administration, configuring power management on mobile devices or sharing an internet connection. To be better able to fulfill this goal, we strongly rely on users who report bugs, send in feature requests and ideas for improvements, and of course participate in development.</p>
	<p>Although this might sound like a distro for Linux newbies, these are not our only target audience, Chakra is made also for techy people and competent GNU/Linux users with a passion for KDE, KISS and such stuff, who don't fear to get their hands dirty but want to set up a usable desktop system quickly and easily.</p>
	<h2>Freedom</h2>
	<p>"Free software" is a matter of liberty, not just price. Chakra and all its appendant software and scripts are <a href="http://www.gnu.org">free software</a>, as in “free speech”, not as in “free beer”. We are proud to develop free software, because it makes a difference. However, to offer our users the smoothest possible experience we occasionally bend the rules and bundle proprietary drivers and software if no viable free alternative is available. As we also believe in choice, all proprietary software can be disabled at system startup (for drivers) and in our installer (for anything else).</p>
	<h1>Legal</h1>
	<h2>Disclaimer</h2>
	<p>No warranties, either express or implied, are hereby given for anything provided by the Chakra Project ("Software"). All software is supplied without any accompanying guarantee, whether expressly mentioned, implied or tacitly assumed. This information does not include any guarantees regarding quality, does not describe any fair marketable quality, and does not make any claims as to quality quarantees or quarantees regarding the suitability for a special purpose. The user assumes all responsibility for damages resulting from the use of the software, including, but not limited to, frustration, disgust, system abends, disk head-crashes, general malfeasance, floods, fires, shark attack, locust infestation, cyclones, hurricanes, tsunamis, local electromagnetic disruptions, hydraulic brake system failure, invasion, hashing collisions, normal wear and tear of friction surfaces, cosmic radiation, inadvertent destruction of sensitive electronic components, windstorms, the riders of nazgul, infuriated chickens, premature activation of a distant early warning system, peasant uprisings, halitosis, artillery bombardment, explosions, cave-ins, borg-assimilation and/or frogs falling from the sky.</p>
	<h2>Donate</h2>
	<p>The Chakra LiveCD, our appendant tools and the packages are built by a small community of developers and packagers, each making their own special contribution. This site is a showcase for our collective work and is built to inform about and celebrate free software.</p>
	<p>Of course these contributions are not everything that is done to keep the project alive and rocking. There are running costs like the rental of our main server and the traffic it generates, and of course the electricity bills of our packagers.</p>
	<p>If technical development, documentation, or support aren't your strong points, making a donation to this project is your opportunity to help us out a bit and enable us to care more about the stuff we like to do, instead of always having an eye on the running costs.</p>
	<p>Many thanks in advance for each donation!</p>
	<table class="centered" width="926px" border="0" align="center">
		<tr>
			<!--<th width="160px" align="center">
				Donate via PayPal: <br/> <br/>
				<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
					<input type="hidden" name="cmd" value="_s-xclick" />
					<input type="hidden" name="encrypted" value="-----BEGIN PKCS7-----MIIHXwYJKoZIhvcNAQcEoIIHUDCCB0wCAQExggEwMIIBLAIBADCBlDCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb20CAQAwDQYJKoZIhvcNAQEBBQAEgYCPY3Yt6fX634adXHfHHY/HI86487EbuG4LDG6vslLIKUU9xGaTjnuw9mRwLRxvrJ/xSApM//4DZFOL67Th0IUEq3Uv7GwoeWGer/RtbztlVzzeFo+nYzMGhdRQWNsCEnEMM9ChdGD10yD2nHO9sAaPPl3xZiUtoT41ZPQAHj/+PjELMAkGBSsOAwIaBQAwgdwGCSqGSIb3DQEHATAUBggqhkiG9w0DBwQIaL9RP++YqH6AgbjTUoKjXAchzvYRXN/LcKamPk4NdmFMQsHaU1Gmxj2tZCZ3bc7k3uxR5jDaojfLJ7rCoijtHDR3c+Rj927R/Z00H+UY7fdIX8t6M1DsYgskoj5oCWtRTHdh28wU4DwR8vHUhmk0hmaovzFhQ+xpJm00vPyfNtPls9bwNhNfssR8RyHQN91gkXW27Z3SdkB1jSqZQocXJnOhvkzpXlZD0ZbRykID3Ly6TH/Hcud7NlZJbsvHT6w+tlUgoIIDhzCCA4MwggLsoAMCAQICAQAwDQYJKoZIhvcNAQEFBQAwgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tMB4XDTA0MDIxMzEwMTMxNVoXDTM1MDIxMzEwMTMxNVowgY4xCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJDQTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIGA1UEChMLUGF5UGFsIEluYy4xEzARBgNVBAsUCmxpdmVfY2VydHMxETAPBgNVBAMUCGxpdmVfYXBpMRwwGgYJKoZIhvcNAQkBFg1yZUBwYXlwYWwuY29tMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDBR07d/ETMS1ycjtkpkvjXZe9k+6CieLuLsPumsJ7QC1odNz3sJiCbs2wC0nLE0uLGaEtXynIgRqIddYCHx88pb5HTXv4SZeuv0Rqq4+axW9PLAAATU8w04qqjaSXgbGLP3NmohqM6bV9kZZwZLR/klDaQGo1u9uDb9lr4Yn+rBQIDAQABo4HuMIHrMB0GA1UdDgQWBBSWn3y7xm8XvVk/UtcKG+wQ1mSUazCBuwYDVR0jBIGzMIGwgBSWn3y7xm8XvVk/UtcKG+wQ1mSUa6GBlKSBkTCBjjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtQYXlQYWwgSW5jLjETMBEGA1UECxQKbGl2ZV9jZXJ0czERMA8GA1UEAxQIbGl2ZV9hcGkxHDAaBgkqhkiG9w0BCQEWDXJlQHBheXBhbC5jb22CAQAwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQUFAAOBgQCBXzpWmoBa5e9fo6ujionW1hUhPkOBakTr3YCDjbYfvJEiv/2P+IobhOGJr85+XHhN0v4gUkEDI8r2/rNk1m0GA8HKddvTjyGw/XqXa+LSTlDYkqI8OwR8GEYj4efEtcRpRYBxV8KxAW93YDWzFGvruKnnLbDAF6VR5w/cCMn5hzGCAZowggGWAgEBMIGUMIGOMQswCQYDVQQGEwJVUzELMAkGA1UECBMCQ0ExFjAUBgNVBAcTDU1vdW50YWluIFZpZXcxFDASBgNVBAoTC1BheVBhbCBJbmMuMRMwEQYDVQQLFApsaXZlX2NlcnRzMREwDwYDVQQDFAhsaXZlX2FwaTEcMBoGCSqGSIb3DQEJARYNcmVAcGF5cGFsLmNvbQIBADAJBgUrDgMCGgUAoF0wGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMTAwNjAyMTkxOTMwWjAjBgkqhkiG9w0BCQQxFgQUF1ECFQO1t6JP/F1jjkJC7RG+YKkwDQYJKoZIhvcNAQEBBQAEgYBwQhF0kR7fSOJHQPTP8HCWxJ1FNr9Rj4TydGxi6lSMyxdQzRS7o/ADGUHZic+VxERUBA4biwEi2Zw+KgdqkmwYDRCQfeQywImBZSeeez3XLm7Vvdw1s8yHPSKZC0EE25eaFwpqhjisx/ODsUmOOS4UdCkN77U5DA7qz0vg+cmmNw==-----END PKCS7-----" />
					<input type="image" src="https://www.paypal.com/en_US/GB/i/btn/btn_donateCC_LG.gif" name="submit" alt="PayPal - The safer, easier way to pay online." />
					<img alt="" border="0" src="https://www.paypal.com/it_IT/i/scr/pixel.gif" width="1" height="1" />
				</form>
			</th> -->
			<th width="160px" align="center">
				Donate via Flattr: <br/> <br/>
				<a class="FlattrButton" style="display:none;" href="http://www.chakraos.org"></a>
			</th>
		</tr>
	</table>
	<p>If you want to donate something else, like a box of tasty cornflakes or one of your hamsters, just write a mail to <a href="mailto:chakra-cabal@googlegroups.com">chakra-cabal@googlegroups.com</a> and we'll figure that out.</p>
	<h3>Usage of donations</h3>
	<p>Donations are mainly used to cover our running expenses, and to make sure that we can adapt our infrastructure to possible increases of users and visitors of our site.</p>
	<p>Any possible overplusses will be used for stuff like travel costs for developer meetings and helping out our developers and packagers on special occasions, like replacing broken hardware for example.</p>
	<h3>Donation status</h3>
	<p>We try to be fully open about what we do with donations. Please check out the <a href="wiki/index.php/Donation_Status">donation status page</a> in our Wiki.</p>
	<h3>Donation conditions</h3>
	<p>A donation is not associated with any rights or privileges. A donation is not associated with any right to a say about its application. Because we care about privacy, all donations will be kept anonymous by default and contributors will not be published or imparted. However, if you want to appear on our public list of donators, tell us. Donation receipts relevant for taxes can not be issued, because the Chakra Project is not a charitable organization or a registered association. From a judicial point of view, all donations are private gifts to the developers of the Chakra Project</p>
	<h1>Chakra Community Code of Conduct</h1>
	<h2>Preamble</h2>
	<p>In the Chakra community, participants from all over the world come together to create, distribute and make use of Free Software for the desktop. This is made possible by the support, hard work and enthusiasm of thousands of people, including those who create and use KDE software.</p>
	<p>This document offers some guidance to ensure Chakra participants can cooperate effectively in a positive and inspiring atmosphere, and to explain how together we can strengthen and support each other.</p>
	<p>This Code of Conduct is shared by all contributors and users who engage with the Chakra team and its community services.</p>
	<h2>Overview</h2>
	<p>This Code of Conduct presents a summary of the shared values and “common sense” thinking in our community. The basic social ingredients that hold our project together include:</p>
	<ul>
	<li>Be considerate</li>
	<li>Be respectful</li>
	<li>Be collaborative</li>
	<li>Be pragmatic</li>
	<li>Support others in the community</li>
	<li>Get support from others in the community</li>
	</ul>
	<p>Our community is made up of several groups of individuals and organizations which can roughly be divided into two groups:</p>
	<ul>
	<li>Contributors, or those who add value to the project through improving Chakra and KDE software as well as its services</li>
	<li>Users, or those who add value to the project through their support as consumers of Chakra and KDE software</li>
	</ul>
	<p>This Code of Conduct reflects the agreed standards of behavior for members of the Chakra community, in any forum, mailing list, wiki, web site, IRC channel, public meeting or private correspondence within the context of the Chakra team and its services. The community acts according to the standards written down in this Code of Conduct and will defend these standards for the benefit of the community. Leaders of any group, such as moderators of mailing lists, IRC channels, forums, etc., will exercise the right to suspend access to any person who persistently breaks our shared Code of Conduct.</p>
	<h2>Be considerate</h2>
	<p>Your actions and work will affect and be used by other people and you in turn will depend on the work and actions of others. Any decision you take will affect other community members, and we expect you to take those consequences into account when making decisions.</p>
	<p>As a contributor, ensure that you give full credit for the work of others and bear in mind how your changes affect others. It is also expected that you try to follow the development schedule and guidelines.</p>
	<p>As a user, remember that contributors work hard on their part of Chakra and KDE - and take great pride in it. If you are frustrated your problems are more likely to be resolved if you can give accurate and well-mannered information to all concerned.</p>
	<h2>Be respectful</h2>
	<p>In order for the Chakra community to stay healthy its members must feel comfortable and accepted. Treating one another with respect is absolutely necessary for this. In a disagreement, in the first instance assume that people mean well.</p>
	<p>We do not tolerate personal attacks, racism, sexism or any other form of discrimination. Disagreement is inevitable, from time to time, but respect for the views of others will go a long way to winning respect for your own view. Respecting other people, their work, their contributions and assuming well-meaning motivation will make community members feel comfortable and safe and will result in motivation and productivity.</p>
	<p>We expect members of our community to be respectful when dealing with other contributors, users and communities. Remember that Chakra is an international project and that you may be unaware of important aspects of other cultures.</p>
	<h2>Be collaborative</h2>
	<p>The Free Software Movement depends on collaboration: it helps limit duplication of effort while improving the quality of the software produced. In order to avoid misunderstanding, try to be clear and concise when requesting help or giving it. Remember it is easy to misunderstand emails (especially when they are not written in your mother tongue). Ask for clarifications if unsure how something is meant; remember the first rule &mdash; assume in the first instance that people mean well.</p>
	<p>As a contributor, you should aim to collaborate with other community members, as well as with other communities that are interested in or depend on the work you do. Your work should be transparent and be fed back into the community when available, not just when Chakra or KDE releases. If you wish to work on something new in existing projects, keep those projects informed of your ideas and progress.</p>
	<p>It may not always be possible to reach consensus on the implementation of an idea, so don't feel obliged to achieve this before you begin. However, always ensure that you keep the outside world informed of your work, and publish it in a way that allows outsiders to test, discuss and contribute to your efforts.</p>
	<p>Contributors on every project come and go. When you leave or disengage from the project, in whole or in part, you should do so with pride about what you have achieved and by acting responsibly towards others who come after you to continue the project.</p>
	<p>As a user, your feedback is important, as is its form. Poorly thought out comments can cause pain and the demotivation of other community members, but considerate discussion of problems can bring positive results. An encouraging word works wonders.</p>
	<h2>Be pragmatic</h2>
	<p>Chakra is a pragmatic community. We value tangible results over having the last word in a discussion. We defend our core values like freedom and respectful collaboration, but we don't let arguments about minor issues get in the way of achieving more important results. We are open to suggestions and welcome solutions regardless of their origin. When in doubt support a solution which helps getting things done over one which has theoretical merits, but isn't being worked on. Use the tools and methods which help getting the job done. Let decisions be taken by those who do the work.</p>
	<h2>Support others in the community</h2>
	<p>Our community is made strong by mutual respect, collaboration and pragmatic, responsible behavior. Sometimes there are situations where this has to be defended and other community members need help.</p>
	<p>If you witness others being attacked, think first about how you can offer them personal support. If you feel that the situation is beyond your ability to help individually, go privately to the victim and ask if some form of official intervention is needed. Similarly you should support anyone who appears to be in danger of burning out, either through work-related stress or personal problems.</p>
	<p>When problems do arise, consider respectfully reminding those involved of our shared Code of Conduct as a first action. Leaders are defined by their actions, and can help set a good example by working to resolve issues in the spirit of this Code of Conduct before they escalate.</p>
	<h2>Get support from others in the community</h2>
	<p>Disagreements, both political and technical, happen all the time. Our community is no exception to the rule. The goal is not to avoid disagreements or differing views but to resolve them constructively. You should turn to the community to seek advice and to resolve disagreements and where possible consult the team most directly involved.</p>
	<p>Think deeply before turning a disagreement into a public dispute. If necessary request mediation, trying to resolve differences in a less highly-emotional medium. If you do feel that you or your work is being attacked, take your time to breathe through before writing heated replies. Consider a 24-hour moratorium if emotional language is being used &mdash; a cooling off period is sometimes all that is needed. If you really want to go a different way, then we encourage you to publish your ideas and your work, so that it can be tried and tested.</p>
	<p><em>This document is licensed under the Creative Commons Attribution - Share Alike 3.0 License. Based on the <a href="http://www.kde.org/code-of-conduct/">KDE Community Code of Conduct</a>.</em></p>
	<p><em>The authors of this document would like to thank the KDE community and those who have worked to create such a dynamic environment to share in and who offered their thoughts and wisdom in the authoring of this document. We would also like to thank other vibrant communities that have helped shape this document with their own examples, such as the Ubuntu community and their Code of Conduct.</em></p>
</div>
