<div class="col-md-12">
    <h1>Ways to contribute financially to Chakra</h1>
    <p>Chakra is a completely community based distribution and all our contributors and developers are working in their free time to provide it.</p>
    <p>The only expenses we have at the moment are for maintaining the main server, through which we provide you Chakra and all the surrounding services. Due to the generous sponsorship by HOST1PLUS, we get a significant discount for the server, with the final cost being around 80 EUR (100 USD) per month, which sums up to 960 EUR (1200 USD) per year.</p>
    <p>This page is for all of you that wish in one way or another to donate money and help Chakra to be self-sustainable by its users. We can only state how deeply amazed we are by your commitment and greatly appreciate your support and love for this distribution! This is one more reason to work harder to reach our goals.</p>
    <h2>Click&Pledge</h2>
    <p>Donate via Click&Pledge to Chakra</p>
    <a href="https://co.clickandpledge.com/advanced/default.aspx?wid=92751"><img src="img/click_and_pledge.png" alt="Donate via Click&Pledge to Chakra" /></a>
    <h2>Paypal</h2>
    <p>Direct donations through credit cards or bank accounts</p>
    <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top"><input type="hidden" name="cmd" value="_s-xclick"><input type="hidden" name="hosted_button_id" value="9D8D3YXKD93U8"><input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1"></form>
    <h2>Flattr</h2>
    <p>Micro-donations on scheduled intervals</p>
    <a href="http://flattr.com/thing/78621/The-Chakra-Project" target="_blank"><img src="http://api.flattr.com/button/flattr-badge-large.png" alt="Flattr this" title="Flattr Chakra" border="0" /></a><br />
    <h2>DuckDuckGo</h2>
    <p>A privacy aware web search engine which shares 50% of its revenue with Chakra, generated by advertisement clicks with Chakra identification enabled</p>
    <a href=" http://chakraos.org/wiki/index.php?title=DuckDuckGo"><img src="http://duckduckgo.com/assets/badges/duckduckgo.png" alt="DuckDuckGo" title="Instructions" border="0" /></a><br />
    <h2>Unixstickers</h2>
    <p>Shop for Chakra stickers, with 15% of the revenue donated back to Chakra</p>
    <a class="serendipity_image_link" title="Chakra Stickers" href='http://www.unixstickers.com/tag/chakra'><!-- s9ymdb:4 --><img class="serendipity_image_center" width="120" height="23"  src="/news/uploads/unixstickers1.png" title="Chakra Stickers" alt="" /></a><br />
    <h2>Zazzle</h2>
    <p>Shop for Chakra branded mugs etc, with 12% of the revenue shared with Chakra</p>
    <a class="serendipity_image_link" title="Chakra shop" href='http://www.zazzle.com/thechakraproject'><!-- s9ymdb:5 --><img class="serendipity_image_center" width="160" height="20"  src="/news/uploads/zazzleLogo_468x60.jpg" title="Chakra shop" alt="" /></a>
</div>
