<?php #

/**
 *  @author Martin Matu�ka <martin@matuska.org>
 *  EN-Revision: Revision of lang_en.inc.php
 */

@define('PLUGIN_KARMA_NAME', 'Karma');
@define('PLUGIN_KARMA_BLAHBLAH', '�itatelia hodnotia kvalitu Va�ich �l�nkov');
@define('PLUGIN_KARMA_VOTETEXT', 'Hodnotenie tohto �l�nku: ');
@define('PLUGIN_KARMA_VOTETEXT_NAME', 'Spr�va pri hodnotiacom pruhu');
@define('PLUGIN_KARMA_VOTETEXT_NAME_BLAHBLAH', 'Text pou�it� p�i zobrazen� pruhu pre hlasovanie.  (Prednastaven�: \'' . PLUGIN_KARMA_VOTETEXT . '\')');
@define('PLUGIN_KARMA_RATE', 'Hodnoti� tento �l�nok: %s');
@define('PLUGIN_KARMA_VOTEPOINT_5', 'Ve�mi dobr�');
@define('PLUGIN_KARMA_VOTEPOINT_5_NAME', 'N�zov najlep�ieho hodnotenia');
@define('PLUGIN_KARMA_VOTEPOINT_5_BLAHBLAH', 'Text pre najlep�ie hodnotenie. (Prednastaven�: \'' . PLUGIN_KARMA_VOTEPOINT_5 . '\')');
@define('PLUGIN_KARMA_VOTEPOINT_4', 'Dobr�');
@define('PLUGIN_KARMA_VOTEPOINT_4_NAME', 'N�zov dobr�ho hodnotenia');
@define('PLUGIN_KARMA_VOTEPOINT_4_BLAHBLAH', 'Text dobr�ho hodnotenia. (Prednastaven�: \'' . PLUGIN_KARMA_VOTEPOINT_4 . '\')');
@define('PLUGIN_KARMA_VOTEPOINT_3', 'Priemer');
@define('PLUGIN_KARMA_VOTEPOINT_3_NAME', 'N�zov neutr�lneho hodnotenia');
@define('PLUGIN_KARMA_VOTEPOINT_3_BLAHBLAH', 'Text neutr�lneho hodnotenia. (Prednastaven�: \'' . PLUGIN_KARMA_VOTEPOINT_3 . '\')');
@define('PLUGIN_KARMA_VOTEPOINT_2', 'Slab�');
@define('PLUGIN_KARMA_VOTEPOINT_2_NAME', 'N�zov slab�ho hodnotenia');
@define('PLUGIN_KARMA_VOTEPOINT_2_BLAHBLAH', 'Text slab�ho hodnotenia. (Prednastaven�: \'' . PLUGIN_KARMA_VOTEPOINT_2 . '\')');
@define('PLUGIN_KARMA_VOTEPOINT_1', 'Zl�');
@define('PLUGIN_KARMA_VOTEPOINT_1_NAME', 'N�zov najhor�ieho hodnotenia');
@define('PLUGIN_KARMA_VOTEPOINT_1_BLAHBLAH', 'Text najhor�ieho hodnotenia. (Prednastaven�: \'' . PLUGIN_KARMA_VOTEPOINT_1 . '\')');
@define('PLUGIN_KARMA_VOTETEXT_5', '+2');
@define('PLUGIN_KARMA_VOTETEXT_5_NAME', 'Hodnota nejlep�ieho hodnotenia');
@define('PLUGIN_KARMA_VOTETEXT_5_BLAHBLAH', 'Text, ktor� sa zobraz� ako hodnota najlep�ieho hodnotenia v hodnotiacom pruhu. (Prednastaven�: ' . PLUGIN_KARMA_VOTETEXT_5 . ')');
@define('PLUGIN_KARMA_VOTETEXT_4', '+1');
@define('PLUGIN_KARMA_VOTETEXT_4_NAME', 'Hodnota dobr�ho hodnotenia');
@define('PLUGIN_KARMA_VOTETEXT_4_BLAHBLAH', 'Text, ktor� sa zobraz� ako hodnota dobr�ho hodnotenia v hodnotiacom pruhu. (Prednastaven�: ' . PLUGIN_KARMA_VOTETEXT_4 . ')');
@define('PLUGIN_KARMA_VOTETEXT_3', '0');
@define('PLUGIN_KARMA_VOTETEXT_3_NAME', 'Hodnota neutr�ln�ho hodnocen�');
@define('PLUGIN_KARMA_VOTETEXT_3_BLAHBLAH', 'Text, ktor� sa zobraz� ako hodnota neutr�lneho hodnotenia v hodnotiacom pruhu. (Prednastaven�: ' . PLUGIN_KARMA_VOTETEXT_3 . ')');
@define('PLUGIN_KARMA_VOTETEXT_2', '-1');
@define('PLUGIN_KARMA_VOTETEXT_2_NAME', 'Hodnota slab�ho hodnocen�');
@define('PLUGIN_KARMA_VOTETEXT_2_BLAHBLAH', 'Text, ktor� sa zobraz� ako hodnota slab�ho hodnotenia v hodnotiacompruhu. (Prednastaven�: ' . PLUGIN_KARMA_VOTETEXT_2 . ')');
@define('PLUGIN_KARMA_VOTETEXT_1', '-2');
@define('PLUGIN_KARMA_VOTETEXT_1_NAME', 'Hodnota nejhor��ho hodnocen�');
@define('PLUGIN_KARMA_VOTETEXT_1_BLAHBLAH', 'Text, ktor� se zobraz� ako hodnota najhor�ieho hodnotenia v hodnotiacom pruhu. (Prednastaven�: ' . PLUGIN_KARMA_VOTETEXT_1 . ')');
@define('PLUGIN_KARMA_VOTED', 'Va�e hodnotenie "%s" bolo zaznamenan�.');
@define('PLUGIN_KARMA_VOTES', '%3$s hlas(ov)');
@define('PLUGIN_KARMA_INVALID', 'Va�e hlasovanie je neplatn�.');
@define('PLUGIN_KARMA_ALREADYVOTED', 'U� ste odovzdali V� hlas.');
@define('PLUGIN_KARMA_NOCOOKIE', 'V� prehliada� mus� podporova� cookies, inak nem��ete hlasova�.');
@define('PLUGIN_KARMA_CLOSED', 'Hodnotenie �l�nku nov�ie ako %s dn�!');
@define('PLUGIN_KARMA_ENTRYTIME', '�as pre hodnotenie po zverejnen� �l�nku.');
@define('PLUGIN_KARMA_ENTRYTIME_BLAHBLAH', 'Ako dlho (v min�tach) po zverejnen� �l�nku je povolen� jeho neobmedzen� hodnotenie? Prednastaven�: 1400 (jeden de�)');
@define('PLUGIN_KARMA_VOTINGTIME', '�as pre hodnotenie');
@define('PLUGIN_KARMA_VOTINGTIME_BLAHBLAH', 'Ako dlho (v min�tach) je potrebn� �aka� medzi dvoma hodnoteniami. Prednastaven�: 5');
@define('PLUGIN_KARMA_TIMEOUT', 'Ochrana pred floodom serveru: In� �itate� pr�ve hlasoval. Pros�m po�kajte s Va��m hlasovan�m %s min�t.');
@define('PLUGIN_KARMA_CURRENT', 'Aktu�lna karma: %2$s, %3$s hlas(ov)');
@define('PLUGIN_KARMA_CURRENT_NAME', 'Spr�va aktu�lneho hodnotenia');
@define('PLUGIN_KARMA_CURRENT_NAME_BLAHBLAH', 'Text pou�it� pri zobrazen� s��asn�ho hodnotenia (%2$s je ��seln� hodnotenie; %3$s je po�et hlasov) (Prednastaven�: ' . PLUGIN_KARMA_CURRENT . ')');
@define('PLUGIN_KARMA_EXTENDEDONLY', 'Iba pri celom �l�nku');
@define('PLUGIN_KARMA_EXTENDEDONLY_BLAHBLAH', 'Zobrazova� hodnotenie iba pri zobrazen� cel�ho �l�nku (roz��renej textovej �asti).');
@define('PLUGIN_KARMA_MAXKARMA', 'Obdobie pre karmu');
@define('PLUGIN_KARMA_MAXKARMA_BLAHBLAH', 'Zapn� hlasovanie pre �l�nok, ktor� je mlad�� ako X dn� (Prednastaven�: 7)');
@define('PLUGIN_KARMA_MIN_DISPLAYABLE_VOTES', 'Minim�lny po�et hlasov na zobrazenie');
@define('PLUGIN_KARMA_MIN_DISPLAYABLE_VOTES_BLAHBLAH', 'Zobrazi� hodnotenie a� ke� po�et hlasov presiahne tu uveden� hodnotu. Ak chcete zobrazova� hodnotenie v�dy, zadajte hodnotu 0.');
@define('PLUGIN_KARMA_LOGGING', 'Logova� hlasy?');
@define('PLUGIN_KARMA_LOGGING_BLAHBLAH', 'Maj� by� inform�cie o hlasovan� logovan�?');
@define('PLUGIN_KARMA_ACTIVE', 'Zapn� hlasovanie?');
@define('PLUGIN_KARMA_ACTIVE_BLAHBLAH', 'Je hlasovanie zapnut�?');
//--JAM:@define('PLUGIN_KARMA_ALIGNMENT', 'Voting Bar Alignment');
//--JAM:@define('PLUGIN_KARMA_ALIGNMENT_BLAHBLAH', 'Alignment of voting bar in the entry footer.  Templates can override this setting with !important (Default: right)');
//--JAM: @define('PLUGIN_KARMA_ALIGNMENT_DETECT', 'from style');
@define('PLUGIN_KARMA_VISITS', 'Zapn� sledovanie n�v�tev?');
@define('PLUGIN_KARMA_VISITS_BLAHBLAH', 'M� by� ka�d� kliknutie na zobrazenie roz��renej textovej �asti po��tan� a zaznamen�van�?');
@define('PLUGIN_KARMA_VISITSCOUNT', ' %4$s zobrazen�');
@define('PLUGIN_KARMA_STATISTICS_VISITS_TOP', 'Naj��tanej�ie �l�nky');
@define('PLUGIN_KARMA_STATISTICS_VISITS_BOTTOM', 'Najmenej ��tan� �l�nky');
@define('PLUGIN_KARMA_STATISTICS_VOTES_TOP', '�l�nky s najviac hlasmi');
@define('PLUGIN_KARMA_STATISTICS_VOTES_BOTTOM', '�l�nky s najmenej hlasmi');
@define('PLUGIN_KARMA_STATISTICS_POINTS_TOP', '�l�nky s najlep��m hodnoten�m');
@define('PLUGIN_KARMA_STATISTICS_POINTS_BOTTOM', '�l�nky s najhor��m hodnoten�m');
@define('PLUGIN_KARMA_STATISTICS_VISITS_NO', 'pre��tan�');
@define('PLUGIN_KARMA_STATISTICS_VOTES_NO', 'hlasov');
@define('PLUGIN_KARMA_STATISTICS_POINTS_NO', 'bodov');

@define('PLUGIN_KARMA_STARRATING', 'Zapn� individu�lne hodnotenie �l�nkov?');

@define('PLUGIN_KARMA_VISITS_LOGGEDIN_USERS', 'Sledova� n�v�tevy prihl�sen�ch pou��vate�ov?');
@define('PLUGIN_KARMA_VISITS_LOGGEDIN_USERS_BLAHBLAH', 'Ak je zapnut�, n�v�tevy prihl�sen�ch pou��vate�ov s� tie� zaznamen�van�. (Medzi t�chto pou��vate�ov patr�te aj vy pri vkladan� nov�ch �l�nkov a ich �prave)');
@define('PLUGIN_KARMA_MIN_DISPLAYABLE_VISITS', 'Minim�lny po�et n�v�tev pre zobrazenie');
@define('PLUGIN_KARMA_MIN_DISPLAYABLE_VISITS_BLAHBLAH', 'Po�et n�v�tev bude zobrazen� a� ked ich po�et prekro�� tu uveden� hodnotu. Ak chcete po��tadlo zobrazova� v�dy, zadajte hodnotu 0.');
@define('PLUGIN_KARMA_WORDRATING', 'Zobrazova� hodnotenie v slovnej forme?');
@define('PLUGIN_KARMA_WORDRATING_BLAHBLAH', 'Chcete zobrazova� hodnotenie ako slov� alebo ��sla? (Prednastaven�: NIE; pou�i� ��seln� hodnotenie)');
@define('PLUGIN_KARMA_IMAGE_WITH_MESSAGE', 'Zobrazova� hodnotiacu spr�vu?');
@define('PLUGIN_KARMA_IMAGE_WITH_MESSAGE_BLAHBLAH', 'Zobrazi� spr�vu pri hodnotiacom pruhu? (nem� na pruhy �iaden efekt) (Prednastaven�: �no)');
@define('PLUGIN_KARMA_IMAGE_WITH_CURR', 'Zobrazi� textov� spr�vu spolu s aktu�lnym hodnoten�m?');
@define('PLUGIN_KARMA_IMAGE_WITH_CURR_BLAHBLAH', 'Zobrazova� textov� inform�cie za grafick�mi pruhmi? (nem� na pruhy �iaden efekt) (Prednastaven�: �no)');
@define('PLUGIN_KARMA_IMAGE_WITH_VISITS', 'Zobrazovat text n�v�tev?');
@define('PLUGIN_KARMA_IMAGE_WITH_VISITS_BLAHBLAH', 'Vlo�i� po�et n�v�t�v aj ako text? (za pruhy, nem� na pruhy �iaden efekt) (Prednastaven�: �no)');
@define('PLUGIN_KARMA_PREVIEW_BG', 'Pozadie pre tabu�ku n�h�adu, uveden� ni��ie');
@define('PLUGIN_KARMA_PREVIEW_BG_BLAHBLAH', 'Platn� je ak�ko�vek hodnota CSS �t�lov; bude pou�it� ako atrib�t \'background\' pre tabu�ku s n�h�adom, a to IBA na administr�torskej str�nke. Nem� �iaden efekt na pruhy s hodnoten�m.');
@define('PLUGIN_KARMA_IMAGE', 'Typ hlasovac�ch pruhov');
@define('PLUGIN_KARMA_IMAGE_DESC', 'Vyberte s�bor s obr�zkom (napr. diamonds.png) pre hlasov�nie s obr�zkami. Vyberte \'' . PLUGIN_KARMA_STATISTICS_POINTS_NO . '\' pre hlasovanie pomocou textu.');
@define('PLUGIN_KARMA_NO_IMAGES', 'V prie�inku img/ doplnku karma nie s� �iadne obr�zky!');
@define('PLUGIN_KARMA_IMAGE_RATING', '%1.2f z 5');
@define('PLUGIN_KARMA_IMAGE_INT_RATING', '%d z 5');
@define('PLUGIN_KARMA_IMAGE_NONE_RATING', '�iadny');
@define('PLUGIN_KARMA_TAB_OPTIONS', 'Nastavenia');
@define('PLUGIN_KARMA_TAB_APPEARANCE', 'Vzh�ad');
@define('PLUGIN_KARMA_TAB_TEXT', 'Text');
@define('PLUGIN_KARMA_DISPLAY_LOG', 'Spr�va Karmy');
@define('PLUGIN_KARMA_REMOVED_POINTS', '%s hlasov odstr�nen�ch z �l�nku %s');
@define('PLUGIN_KARMA_APPROVED_POINTS', '%s hlasov pre �l�nok %s potvrden�ch');
@define('PLUGIN_KARMA_POINTS_ERROR', 'Chyba pri aktualiz�cii hlasov pre �l�nok %s!');
@define('PLUGIN_KARMA_REMOVE_ERROR', 'Chyba pri odstra�ovan� hlasov pre �l�nok %s! (Po�et bodov bol napriek tomu aktualizovan�.)');
@define('PLUGIN_KARMA_UPDATE_ERROR', 'Zatial �iadne hlasy pre �l�nok %s!');
@define('PLUGIN_KARMA_INVALID_INPUT', 'Nespr�vny vstup!');
@define('PLUGIN_KARMA_DELETE_VOTES', 'Vymaza� vybran� hlasy');
@define('PLUGIN_KARMA_APPROVE_VOTES', 'Potvrdi� vybran� hlasy');

